### ISSUE TITLE
建议还可以改进一下适配，垠神移动端是全屏的

### ISSUE THREAD

**Issue by dazkarieh** [Gracker/hexo-theme-reading#2]
手机端内嵌文本框有些逼仄。

**Comment by Gracker** [comment]
好的。
这个是得这么做。

**Comment by Gracker** [comment]
移动端的适配已经搞好了。

**Comment by dazkarieh** [comment]
浏览没有问题，不过部分渲染失败……
10:18:51.597 DEBUG Rendering index: index.html
GET / 200 95.308 ms - -
10:18:51.953 ERROR Asset render failed: css/home.css
ParseError: /Users/dazkarieh/Public/ian/themes/reading/source/css/home.styl:2:167
   1| body {
   2|   font-family: Palatino Linotype", "Book Antiqua","STFangSong", Helvetica, Arial, Vernada, Tahoma, STXihei, "Microsoft YaHei", "Songti SC", SimSun, Heiti, sans-serif;
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
   3|   font-size: 21px;
   4| }
   5|

expected "indent", got ";" 
    at Parser.error (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:259:11)
    at Parser.expect (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:287:12)
    at Parser.block (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:845:12)
    at Parser.selector (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:1555:24)
    at Parser.stmt (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:685:21)
    at Parser.block (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:852:21)
    at Parser.selector (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:1555:24)
    at Parser.ident (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:1446:25)
    at Parser.stmt (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:685:21)
    at Parser.parse (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/parser.js:236:25)
    at Renderer.render (/Users/dazkarieh/Public/ian/node_modules/stylus/lib/renderer.js:80:22)
    at Hexo.module.exports (/Users/dazkarieh/Public/ian/node_modules/hexo-renderer-stylus/lib/renderer.js:53:6)
    at Hexo.tryCatcher (/Users/dazkarieh/Public/ian/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (/Users/dazkarieh/Public/ian/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/dazkarieh/Public/ian/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dazkarieh/Public/ian/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dazkarieh/Public/ian/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dazkarieh/Public/ian/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dazkarieh/Public/ian/node_modules/bluebird/js/release/promise.js:693:18)
GET /css/home.css?v=3 200 78.620 ms - -
GET /css/bootstrap-theme.min.css 200 81.199 ms - -
GET /css/bootstrap.min.css 200 83.930 ms - -

**Comment by Gracker** [comment]
刚刚已经发行并修改了，你再试试

**Comment by dazkarieh** [comment]
行了，真漂亮~~~
